//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using LinqConnect template.
// Code is generated on: 19.05.2023 10:44:19
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using Devart.Data.Linq;
using Devart.Data.Linq.Mapping;
using System.Data;
using System.ComponentModel;
using System.Collections.Generic;
using System.Reflection;
using System.Linq;
using System.Linq.Expressions;

namespace HomeLibrary
{

    /// <summary>
    /// There are no comments for HomeLibrary.Author in the schema.
    /// </summary>
    [Table(Name = @"home_library.Authors")]
    public partial class Author : INotifyPropertyChanging, INotifyPropertyChanged
    {

        private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(System.String.Empty);
        #pragma warning disable 0649

        private int _AuthorID;

        private string _Name;
        #pragma warning restore 0649

        private EntitySet<Book> _Books;

        #region Extensibility Method Definitions

        partial void OnLoaded();
        partial void OnValidate(ChangeAction action);
        partial void OnCreated();
        partial void OnAuthorIDChanging(int value);
        partial void OnAuthorIDChanged();
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        #endregion

        public Author()
        {
            this._Books = new EntitySet<Book>(new Action<Book>(this.attach_Books), new Action<Book>(this.detach_Books));
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for AuthorID in the schema.
        /// </summary>
        [Column(Storage = "_AuthorID", AutoSync = AutoSync.OnInsert, CanBeNull = false, DbType = "int(9) NOT NULL", IsDbGenerated = true, IsPrimaryKey = true)]
        public int AuthorID
        {
            get
            {
                return this._AuthorID;
            }
        }

    
        /// <summary>
        /// There are no comments for Name in the schema.
        /// </summary>
        [Column(Storage = "_Name", CanBeNull = false, DbType = "longtext NOT NULL", UpdateCheck = UpdateCheck.Never)]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                if (this._Name != value)
                {
                    this.OnNameChanging(value);
                    this.SendPropertyChanging("Name");
                    this._Name = value;
                    this.SendPropertyChanged("Name");
                    this.OnNameChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for Books in the schema.
        /// </summary>
        [Devart.Data.Linq.Mapping.Association(Name="Author_Book", Storage="_Books", ThisKey="AuthorID", OtherKey="AuthorID")]
        public virtual EntitySet<Book> Books
        {
            get
            {
                return this._Books;
            }
            set
            {
                this._Books.Assign(value);
            }
        }
   
        public event PropertyChangingEventHandler PropertyChanging;

        public event PropertyChangedEventHandler PropertyChanged;

        protected virtual void SendPropertyChanging()
        {
            var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, emptyChangingEventArgs);
        }

        protected virtual void SendPropertyChanging(System.String propertyName) 
        {
            var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, new PropertyChangingEventArgs(propertyName));
        }

        protected virtual void SendPropertyChanged(System.String propertyName)
        {
            var handler = this.PropertyChanged;
            if (handler != null)
                handler(this, new PropertyChangedEventArgs(propertyName));
        }

        private void attach_Books(Book entity)
        {
            this.SendPropertyChanging("Books");
            entity.Author = this;
        }
    
        private void detach_Books(Book entity)
        {
            this.SendPropertyChanging("Books");
            entity.Author = null;
        }
    }

}
