//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using LinqConnect template.
// Code is generated on: 15.04.2023 14:38:46
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using Devart.Data.Linq;
using Devart.Data.Linq.Mapping;
using System.Data;
using System.ComponentModel;
using System.Collections.Generic;
using System.Reflection;
using System.Linq;
using System.Linq.Expressions;

namespace ormExample
{

    /// <summary>
    /// There are no comments for ormExample.Department in the schema.
    /// </summary>
    [Table(Name = @"fhooe2.Departments")]
    public partial class Department : INotifyPropertyChanging, INotifyPropertyChanged
    {

        private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(System.String.Empty);
        #pragma warning disable 0649

        private int _DepID;

        private string _Name;

        private string _Abbreviation;
        #pragma warning restore 0649

        private EntitySet<Student> _Students;

        #region Extensibility Method Definitions

        partial void OnLoaded();
        partial void OnValidate(ChangeAction action);
        partial void OnCreated();
        partial void OnDepIDChanging(int value);
        partial void OnDepIDChanged();
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        partial void OnAbbreviationChanging(string value);
        partial void OnAbbreviationChanged();
        #endregion

        public Department()
        {
            this._Students = new EntitySet<Student>(new Action<Student>(this.attach_Students), new Action<Student>(this.detach_Students));
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for DepID in the schema.
        /// </summary>
        [Column(Storage = "_DepID", AutoSync = AutoSync.OnInsert, CanBeNull = false, DbType = "int(9) NOT NULL", IsDbGenerated = true, IsPrimaryKey = true)]
        public int DepID
        {
            get
            {
                return this._DepID;
            }
            set
            {
                if (this._DepID != value)
                {
                    this.OnDepIDChanging(value);
                    this.SendPropertyChanging("DepID");
                    this._DepID = value;
                    this.SendPropertyChanged("DepID");
                    this.OnDepIDChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for Name in the schema.
        /// </summary>
        [Column(Storage = "_Name", DbType = "longtext NULL", UpdateCheck = UpdateCheck.Never)]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                if (this._Name != value)
                {
                    this.OnNameChanging(value);
                    this.SendPropertyChanging("Name");
                    this._Name = value;
                    this.SendPropertyChanged("Name");
                    this.OnNameChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for Abbreviation in the schema.
        /// </summary>
        [Column(Storage = "_Abbreviation", DbType = "longtext NULL", UpdateCheck = UpdateCheck.Never)]
        public string Abbreviation
        {
            get
            {
                return this._Abbreviation;
            }
            set
            {
                if (this._Abbreviation != value)
                {
                    this.OnAbbreviationChanging(value);
                    this.SendPropertyChanging("Abbreviation");
                    this._Abbreviation = value;
                    this.SendPropertyChanged("Abbreviation");
                    this.OnAbbreviationChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for Students in the schema.
        /// </summary>
        [Devart.Data.Linq.Mapping.Association(Name="Department_Student", Storage="_Students", ThisKey="DepID", OtherKey="DepID")]
        public virtual EntitySet<Student> Students
        {
            get
            {
                return this._Students;
            }
            set
            {
                this._Students.Assign(value);
            }
        }
   
        public event PropertyChangingEventHandler PropertyChanging;

        public event PropertyChangedEventHandler PropertyChanged;

        protected virtual void SendPropertyChanging()
        {
            var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, emptyChangingEventArgs);
        }

        protected virtual void SendPropertyChanging(System.String propertyName) 
        {
            var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, new PropertyChangingEventArgs(propertyName));
        }

        protected virtual void SendPropertyChanged(System.String propertyName)
        {
            var handler = this.PropertyChanged;
            if (handler != null)
                handler(this, new PropertyChangedEventArgs(propertyName));
        }

        private void attach_Students(Student entity)
        {
            this.SendPropertyChanging("Students");
            entity.Department = this;
        }
    
        private void detach_Students(Student entity)
        {
            this.SendPropertyChanging("Students");
            entity.Department = null;
        }
    }

}
